// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef OPJ_BOOL (*opj_stream_seek_fn)(OPJ_OFF_T, void *)
 * }
 */
public class opj_stream_seek_fn {

    opj_stream_seek_fn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(long p_nb_bytes, MemorySegment p_user_data);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        openjpeg_h.C_INT,
        openjpeg_h.C_LONG_LONG,
        openjpeg_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = openjpeg_h.upcallHandle(opj_stream_seek_fn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(opj_stream_seek_fn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,long p_nb_bytes, MemorySegment p_user_data) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, p_nb_bytes, p_user_data);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

