// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_tile_index {
 *     OPJ_UINT32 tileno;
 *     OPJ_UINT32 nb_tps;
 *     OPJ_UINT32 current_nb_tps;
 *     OPJ_UINT32 current_tpsno;
 *     opj_tp_index_t *tp_index;
 *     OPJ_UINT32 marknum;
 *     opj_marker_info_t *marker;
 *     OPJ_UINT32 maxmarknum;
 *     OPJ_UINT32 nb_packet;
 *     opj_packet_info_t *packet_index;
 * } opj_tile_index_t
 * }
 */
public class opj_tile_index_t extends opj_tile_index {

    opj_tile_index_t() {
        // Should not be called directly
    }
}

