// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_dparameters {
 *     OPJ_UINT32 cp_reduce;
 *     OPJ_UINT32 cp_layer;
 *     char infile[4096];
 *     char outfile[4096];
 *     int decod_format;
 *     int cod_format;
 *     OPJ_UINT32 DA_x0;
 *     OPJ_UINT32 DA_x1;
 *     OPJ_UINT32 DA_y0;
 *     OPJ_UINT32 DA_y1;
 *     OPJ_BOOL m_verbose;
 *     OPJ_UINT32 tile_index;
 *     OPJ_UINT32 nb_tile_to_decode;
 *     OPJ_BOOL jpwl_correct;
 *     int jpwl_exp_comps;
 *     int jpwl_max_tiles;
 *     unsigned int flags;
 * } opj_dparameters_t
 * }
 */
public class opj_dparameters_t extends opj_dparameters {

    opj_dparameters_t() {
        // Should not be called directly
    }
}

