// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_image_comp {
 *     OPJ_UINT32 dx;
 *     OPJ_UINT32 dy;
 *     OPJ_UINT32 w;
 *     OPJ_UINT32 h;
 *     OPJ_UINT32 x0;
 *     OPJ_UINT32 y0;
 *     OPJ_UINT32 prec;
 *     OPJ_UINT32 bpp;
 *     OPJ_UINT32 sgnd;
 *     OPJ_UINT32 resno_decoded;
 *     OPJ_UINT32 factor;
 *     OPJ_INT32 *data;
 *     OPJ_UINT16 alpha;
 * } opj_image_comp_t
 * }
 */
public class opj_image_comp_t extends opj_image_comp {

    opj_image_comp_t() {
        // Should not be called directly
    }
}

