// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_jp2_metadata {
 *     OPJ_INT32 not_used;
 * } opj_jp2_metadata_t
 * }
 */
public class opj_jp2_metadata_t extends opj_jp2_metadata {

    opj_jp2_metadata_t() {
        // Should not be called directly
    }
}

