// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_codestream_info {
 *     double D_max;
 *     int packno;
 *     int index_write;
 *     int image_w;
 *     int image_h;
 *     OPJ_PROG_ORDER prog;
 *     int tile_x;
 *     int tile_y;
 *     int tile_Ox;
 *     int tile_Oy;
 *     int tw;
 *     int th;
 *     int numcomps;
 *     int numlayers;
 *     int *numdecompos;
 *     int marknum;
 *     opj_marker_info_t *marker;
 *     int maxmarknum;
 *     int main_head_start;
 *     int main_head_end;
 *     int codestream_size;
 *     opj_tile_info_t *tile;
 * } opj_codestream_info_t
 * }
 */
public class opj_codestream_info_t extends opj_codestream_info {

    opj_codestream_info_t() {
        // Should not be called directly
    }
}

