// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_tile_v2_info {
 *     int tileno;
 *     OPJ_UINT32 csty;
 *     OPJ_PROG_ORDER prg;
 *     OPJ_UINT32 numlayers;
 *     OPJ_UINT32 mct;
 *     opj_tccp_info_t *tccp_info;
 * } opj_tile_info_v2_t
 * }
 */
public class opj_tile_info_v2_t extends opj_tile_v2_info {

    opj_tile_info_v2_t() {
        // Should not be called directly
    }
}

