// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_image_comptparm {
 *     OPJ_UINT32 dx;
 *     OPJ_UINT32 dy;
 *     OPJ_UINT32 w;
 *     OPJ_UINT32 h;
 *     OPJ_UINT32 x0;
 *     OPJ_UINT32 y0;
 *     OPJ_UINT32 prec;
 *     OPJ_UINT32 bpp;
 *     OPJ_UINT32 sgnd;
 * } opj_image_cmptparm_t
 * }
 */
public class opj_image_cmptparm_t extends opj_image_comptparm {

    opj_image_cmptparm_t() {
        // Should not be called directly
    }
}

