// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_tp_index {
 *     OPJ_OFF_T start_pos;
 *     OPJ_OFF_T end_header;
 *     OPJ_OFF_T end_pos;
 * } opj_tp_index_t
 * }
 */
public class opj_tp_index_t extends opj_tp_index {

    opj_tp_index_t() {
        // Should not be called directly
    }
}

