// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_codestream_index {
 *     OPJ_OFF_T main_head_start;
 *     OPJ_OFF_T main_head_end;
 *     OPJ_UINT64 codestream_size;
 *     OPJ_UINT32 marknum;
 *     opj_marker_info_t *marker;
 *     OPJ_UINT32 maxmarknum;
 *     OPJ_UINT32 nb_of_tiles;
 *     opj_tile_index_t *tile_index;
 * } opj_codestream_index_t
 * }
 */
public class opj_codestream_index_t extends opj_codestream_index {

    opj_codestream_index_t() {
        // Should not be called directly
    }
}

