// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_tp_info {
 *     int tp_start_pos;
 *     int tp_end_header;
 *     int tp_end_pos;
 *     int tp_start_pack;
 *     int tp_numpacks;
 * } opj_tp_info_t
 * }
 */
public class opj_tp_info_t extends opj_tp_info {

    opj_tp_info_t() {
        // Should not be called directly
    }
}

