// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_codestream_info_v2 {
 *     OPJ_UINT32 tx0;
 *     OPJ_UINT32 ty0;
 *     OPJ_UINT32 tdx;
 *     OPJ_UINT32 tdy;
 *     OPJ_UINT32 tw;
 *     OPJ_UINT32 th;
 *     OPJ_UINT32 nbcomps;
 *     opj_tile_info_v2_t m_default_tile_info;
 *     opj_tile_info_v2_t *tile_info;
 * } opj_codestream_info_v2_t
 * }
 */
public class opj_codestream_info_v2_t extends opj_codestream_info_v2 {

    opj_codestream_info_v2_t() {
        // Should not be called directly
    }
}

