// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_image {
 *     OPJ_UINT32 x0;
 *     OPJ_UINT32 y0;
 *     OPJ_UINT32 x1;
 *     OPJ_UINT32 y1;
 *     OPJ_UINT32 numcomps;
 *     OPJ_COLOR_SPACE color_space;
 *     opj_image_comp_t *comps;
 *     OPJ_BYTE *icc_profile_buf;
 *     OPJ_UINT32 icc_profile_len;
 * } opj_image_t
 * }
 */
public class opj_image_t extends opj_image {

    opj_image_t() {
        // Should not be called directly
    }
}

