// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_marker_info {
 *     unsigned short type;
 *     OPJ_OFF_T pos;
 *     int len;
 * } opj_marker_info_t
 * }
 */
public class opj_marker_info_t extends opj_marker_info {

    opj_marker_info_t() {
        // Should not be called directly
    }
}

