// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_poc {
 *     OPJ_UINT32 resno0;
 *     OPJ_UINT32 compno0;
 *     OPJ_UINT32 layno1;
 *     OPJ_UINT32 resno1;
 *     OPJ_UINT32 compno1;
 *     OPJ_UINT32 layno0;
 *     OPJ_UINT32 precno0;
 *     OPJ_UINT32 precno1;
 *     OPJ_PROG_ORDER prg1;
 *     OPJ_PROG_ORDER prg;
 *     OPJ_CHAR progorder[5];
 *     OPJ_UINT32 tile;
 *     OPJ_INT32 tx0;
 *     OPJ_INT32 tx1;
 *     OPJ_INT32 ty0;
 *     OPJ_INT32 ty1;
 *     OPJ_UINT32 layS;
 *     OPJ_UINT32 resS;
 *     OPJ_UINT32 compS;
 *     OPJ_UINT32 prcS;
 *     OPJ_UINT32 layE;
 *     OPJ_UINT32 resE;
 *     OPJ_UINT32 compE;
 *     OPJ_UINT32 prcE;
 *     OPJ_UINT32 txS;
 *     OPJ_UINT32 txE;
 *     OPJ_UINT32 tyS;
 *     OPJ_UINT32 tyE;
 *     OPJ_UINT32 dx;
 *     OPJ_UINT32 dy;
 *     OPJ_UINT32 lay_t;
 *     OPJ_UINT32 res_t;
 *     OPJ_UINT32 comp_t;
 *     OPJ_UINT32 prc_t;
 *     OPJ_UINT32 tx0_t;
 *     OPJ_UINT32 ty0_t;
 * } opj_poc_t
 * }
 */
public class opj_poc_t extends opj_poc {

    opj_poc_t() {
        // Should not be called directly
    }
}

