// Generated by jextract

package org.openjpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct opj_packet_info {
 *     OPJ_OFF_T start_pos;
 *     OPJ_OFF_T end_ph_pos;
 *     OPJ_OFF_T end_pos;
 *     double disto;
 * } opj_packet_info_t
 * }
 */
public class opj_packet_info_t extends opj_packet_info {

    opj_packet_info_t() {
        // Should not be called directly
    }
}

